services:
  app:
    image: theearloftea/swkom
    ports:
      - "8080:8080"
    environment:
      db-url: jdbc:postgresql://db:5432/postgres
      db-username: postgres
      db-password: postgres
    command: ['java', '-jar', 'swagger-spring-1.0.0.jar']
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /data
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    command: --interval 10
