name: Docker CI

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build Docker Image with Maven
        env:
          db-url: ${{ secrets.DB_URL }}
          db-username: ${{ secrets.DB_USERNAME }}
          db-password: ${{ secrets.DB_PASSWORD }}
        run: mvn spring-boot:build-image -DskipTests
        
      - name: login to docker hub
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: push docker image
        run: docker push ${{secrets.DOCKER_USER}}//${{secrets.DOCKER_REPOSITORY}}

