name: Master CI

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  build-java-applicatio-and-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        env:
          db-url: ${{ secrets.DB_URL }}
          db-username: ${{ secrets.DB_USERNAME }}
          db-password: ${{ secrets.DB_PASSWORD }}
        run: mvn clean install
      - name: make target folder
        run: mkdir ${{github.workspace}}/target
      - name: copy jar to right folder
        run: cp ./target/swagger-spring-1.0.0.jar %{{github.WORKSPACE}}/target
  build-and-push-docker-image:
    needs: build-java-applicatio-and-docker-image
    runs-on: ubuntu-latest
    steps:
      -
        name: check out repository
        uses: actions/checkout@v3
      - name: test repository
        run: echo ${{github.WORKSPACE}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: theearloftea/swkom:latest
          db-url: ${{secrets.DB_URL}}
          db-username: ${{secrets.DB_USERNAME}}
          db-password: ${{secrets.DB_PASSWORD}}
          workspace: ${{github.WORKSPACE}}
      
    
        
