name: Master CI

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-java-application:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        env:
          db-url: ${{ secrets.DB_URL }}
          db-username: ${{ secrets.DB_USERNAME }}
          db-password: ${{ secrets.DB_PASSWORD }}
        run: mvn clean install
        
  build-docker-image:
    needs: build-java-application
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker image
        run: docker build . -t parcel-image --build-arg db-url=${{ secrets.DB_URL }} --build-arg db-username=${{ secrets.DB_USERNAME }} --build-arg db-password=${{ secrets.DB_PASSWORD }}
        
  push-docker-image:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/swkom

